#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &
bash $HOME/.config/polybar/launch.sh &
feh --bg-fill $HOME/bg/* &
picom &

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DVI-0 -d 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           0

bspc config focused_border_color '#0060cc'
bspc config active_border_color '#0e4d92'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Matplotlib state=floating
